### ISSUE TITLE
兄弟你这个项目还搞吗? 不搞我打算fork一份自己搞了.延续她的生命.

### ISSUE THREAD

**Issue by sgf** [SpringLeee/HttpReportsWeb#3]
我搜遍了github 发现.net生态里面这块相关的项目较少.因此她,这个项目应该有她的一席之地.
我技术比较烂,目前也不从事Web开发.
但是我对.net,C# 比较喜欢吧.其实也没什么资源给这个项目,但我觉得至少不会让他一直只读.
你懂我意思吧?

虽然这个项目是MIT协议,但是本对第一作者的尊重.我还是先打个招呼.
并代表.net开源社区感谢您的无私奉献(虽然作为一个小小的码农,我并没有资格说这个话)

我的业余时间也很少.只能 挤挤时间偶尔搞搞这个样子.(不用怀疑,肯定会非常少非常少)
另外,我会放弃一众老旧的.net 版本支持,直接定位到.net 8.0
一些关键性的组件也会考虑替换掉.当然具体的还要看后续.net 整个生态的发展情况.

总之,原则就是:抛开历史包袱,抛开兼容包袱,走自己的路子(包括野路子),怎么舒服怎么来,怎么高效怎么来.
不必要的东西则可能是能省则省,除非有其他人加入维护.

**Comment by SpringLeee** [comment]
@sgf 没问题的，感谢您的支持

**Comment by sgf** [comment]
tks
